graph LR

subgraph Main Actor
Owner[Owner]
end

subgraph Use Cases  
Owner -.Confirmed email.- Register(Register)  
Owner --- Login(Login)  
Owner --- Logout(Logout)  
Owner --- CreateAcc(Successfuly create account)  
Owner --- Setting(Setting working schedule)  
Owner --- Invitation(Send URL invitation)  
Owner --- ScheduleApt(Schedule an appointment)  
Owner --- CheckApt(View all appointment through a calendar-UI)  
Owner --- CancelApt(Cancel appoitnment)  
Owner --- ChangeApt(Change appointment)  
end

subgraph Extended Actors  
NewUser[New User]  
Customer[Customer]  
end  

ScheduleApt --- Customer  
CancelApt --- Customer  
ChangeApt --- Customer  

Register --- NewUser 
